main: io.github.aleksandarharalanov.smartride.core.SmartRides
version: 1.0.0-rc.1
name: SmartRides
author: Beezle
website: github.com/AleksandarHaralanov/SmartRides
description: Allows for full control over pig riding.

commands:
  smartride:
    description: SmartRides main command.
    usage: /<command>
    aliases: [sr]

permissions:
  smartride.*:
    children:
      smartride.summon: true
      smartride.staff: true
    description: All SmartRides permissions.
    default: op
  smartride.summon:
    description: Allows the player to summon a pig ride.
    default: op
  smartride.staff:
    description: Allows the player to run staff-only commands.
    default: op